#27-implement-cqrsmediatr-structure
MaximPyatigor/exsb22-t1 pull request #15
Opened 2022-07-18 08:19 UTC by Saigunas

Implemented CQRS + mediatR folder structure. Added packages, ready to be worked with.
You can see an example on how to use this in the test branch "test_cqrs_and_mediatR".

2022-07-18 08:35 UTC, otash8110 approved these changes

2022-07-18 08:45 UTC, DoniyorJN requested changes

2022-07-18 08:45 UTC, DoniyorJN commented on src/BudgetManager/BudgetManager.CQRS/MediatREntryPoint.cs
> +    {
why do we need this one 
please keep YAGNI principle ?

2022-07-18 09:00 UTC, Saigunas commented on src/BudgetManager/BudgetManager.CQRS/MediatREntryPoint.cs
> +    {
I read online that it was suggested to use another class to make it more readable, as we get specific entry point for mediatR in program.cs.

2022-07-18 11:27 UTC, VladislavGromadtsov approved these changes

2022-07-19 02:05 UTC, sirojbekdev approved these changes

2022-07-19 06:56 UTC, DoniyorJN approved these changes

2022-07-19 06:57 UTC, merged