feat: Added authentication, authorization with jwt token
MaximPyatigor/exsb22-t1 pull request #3
Opened 2022-07-13 12:12 UTC by Saigunas

Authorization and logging in is done with jwt token.
Microsoft identity was only used to get userManager service. Didn't use singInManager as didn't see a point to it right now.
Weather forecast was added to test authorization.
JwtTokenService creates a jwt token, didn't want the controller to do the work. I was not sure where it should be placed so just left it in a folder in API project.

I am not very familiar with "microsoft identity" so I could have not used some of its features that should be used. So please take a look at the code. I know the code is smelly, sorry (×_×#)

2022-07-13 13:31 UTC, otash8110 approved these changes

2022-07-13 14:27 UTC, VladislavGromadtsov requested changes
https://www.c-sharpcorner.com/article/jwt-authentication-with-refresh-tokens-in-net-6-0/
Here the link which can help to make some changes

2022-07-13 14:27 UTC, VladislavGromadtsov commented on API/JwtTokenService/IJwtTokenService.cs
> +}
Interfaces should be stored in separated folder. It's better to do in such way.

2022-07-13 14:27 UTC, VladislavGromadtsov commented on API/Controllers/AuthController.cs
> +        public async Task<IActionResult> Login([Required][EmailAddress] string email, [Required] string password)
i think it will be better to use DTO model with Email and password fields to Login. One DTO for registration and another for login

2022-07-13 14:27 UTC, VladislavGromadtsov commented on API/JwtTokenService/JwtTokenService.cs
> +                expires: DateTime.Now.AddDays(1),
Expiration time should be about 3 hours as we discussed yesterday with Dmitry
```suggestion
                expires: DateTime.Now.AddMinutes(tokenValidityInMinutes),
```
Also tokenValidityInMinutes should be stored in our appsettings

2022-07-15 10:12 UTC, Saigunas commented
Change of plans

2022-07-15 10:12 UTC, closed without merging