#208-exp-03-edit-expense
MaximPyatigor/exsb22-t1 pull request #98
Opened 2022-08-08 20:36 UTC by sirojbekdev

2022-08-08 20:57 UTC, VladislavGromadtsov requested changes

2022-08-08 20:57 UTC, VladislavGromadtsov commented on src/BudgetManager/BudgetManager.SDK/DTOs/UpdateExpenseTransactionDTO.cs
> +        public Guid CategoryId { get; set; }
Update expense should also have SubCategotyId

2022-08-09 08:13 UTC, paulius27 commented on src/BudgetManager/BudgetManager.CQRS/Handlers/TransactionHandlers/UpdateExpenseTransactionHandler.cs
> +            var oldIncomeTransaction = (await _dataAccess.FilterBy<Transaction>(filter, projection, cancellationToken)).FirstOrDefault();
Variable name should be 'oldExpenseTransaction'.

2022-08-09 08:18 UTC, paulius27 approved these changes

2022-08-09 08:48 UTC, otash8110 approved these changes

2022-08-09 10:00 UTC, VladislavGromadtsov approved these changes

2022-08-09 10:49 UTC, merged